### ISSUE TITLE
Autocomplete multiSelect (tags) - backspace deletes tag even if there is text

### ISSUE THREAD

**Issue by thienanle** [ritz078/react-filters#27]
Backspace deletes tag even if there is text.
The expected behavior is backspace should delete text before deleting the previous tag. If there is no text, the latest tag should be deleted.
![oct-16-2016 14-43-38](https://cloud.githubusercontent.com/assets/874402/19415057/fa85172a-93ae-11e6-840c-bf7570aca7ba.gif)

**Comment by ritz078** [comment]
Thanks for the PR. This repo is still a WIP so let me know whenever you find any issue. 😄

**Comment by thienanle** [comment]
No worries @ritz078, it's a great project!
